# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acee00237242e43d2d06e85faf57cbdae8cefe8d7d7189dc6f1da9f5f648313266a8f88eb3e27d8fb0828dd65228f2a0981f37dc81b622a30c04b5584823290f

test:
  secret_key_base: eb0ef49a1f0b8338d1371387275ca89a224c359797d6e5fbbf1c25c37a0f8bd9e285e4bc123a7a75b25a8d869ddac64155b334be3454b99fb0a5fd7dd77fd6e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
